### ISSUE TITLE
log-it-out challenge just doesn't pass test

### ISSUE THREAD

**Issue by ghost** [workshopper/test-anything#16]
I put in the code as the per the challenge "log it out":

```
var emotify = require(process.argv[2]);
console.log(emotify(process.argv[3]);
```

same code as the [solution](https://github.com/finnp/test-anything/blob/master/exercises/log-it-out/solution.md)
but I get:

```
➜  test-anything git:(master) test-anything verify log-it-out.js

TAP version 13
# (anonymous)
not ok 1 adds smiley correctly
  ---
    operator: equal
    expected: '0.5904866035562009test :)\n'
    actual:   ''
    at: ConcatStream.<anonymous> (/usr/local/lib/node_modules/test-anything/node_modules/concat-stream/index.js:36:43)
  ...

1..1
# tests 1
# pass  0
# fail  1

#########################################
###   YOUR SOLUTION IS NOT CORRECT!   ###
#########################################
```

What am I doing wrong?
Thanks!

**Comment by FGummesson** [comment]
The problem is that you don't close the `emotify` function.  :smile:

**Comment by jonasem** [comment]
I got the same error, 1 test passed, 1 failed. Even copied the solution and got the same error...

**Comment by AGhost-7** [comment]
Yep, same here. Either something's wrong with the test or the solution is wrong.

**Comment by finnp** [comment]
I am unable to verify this. What kind of operation systems and node versions (node -v) are you using?

**Comment by jonasem** [comment]
Windows 8 / node v0.10.32 here. Other nodeschools i've tried works fine on this system.

**Comment by mpmckenna8** [comment]
I'm getting the same error running Node v0.10.35 on OSX Yosemite.

**Comment by vgoma** [comment]
Same thing with Node v0.12.2 on OSX Yosemite
