### ISSUE TITLE
No exercises runs my solution

### ISSUE THREAD

**Issue by jonasem** [workshopper/test-anything#17]
I see i get a failing test on all the exercises... Is my syntax for running them wrong?

`$ test-anything verify app.js`

Running any parameter with verify seems to pass all but 1 test, on any exercise...

**Comment by jonasem** [comment]
Have you tested this nodeschool package =) ?

**Comment by finnp** [comment]
This looks correct. What are the errors you are seeing? What's the code you used?

**Comment by vgonsalez** [comment]
Except for exercises "log it out" and "tell me what is wrong", all I can get is a "your solution is not correct!", even if I copy and paste the author solution.

Does it mean my node version is different from yours?

**Comment by jonasem** [comment]
This was 3 years ago, closing due to age, cant remember node version used.
