### ISSUE TITLE
Error just running test-anything on Windows 10

### ISSUE THREAD

**Issue by ghost** [workshopper/test-anything#25]
![image](https://cloud.githubusercontent.com/assets/14023072/15595847/535f2096-2377-11e6-91d2-2bdee9901e3d.png)

**Comment by scott-plutovr** [comment]
I'm running in git-bash installed by Git for Windows located in C:\Program Files\Git\git-bash.exe. They provide git version 2.8.3.windows.1

**Comment by finnp** [comment]
Hey. git-bash had some issues with recent Node versions. I'm not sure if it is fixed with newer versions. But I'd recommend using Windows PowerShell instead.

What was the reason for using git-bash in the first place? Was is recommended somewhere?

**Comment by scott-plutovr** [comment]
No reason other than git-bash was what I have on my computer and I had used
git to pull down the stuff from GitHub that I would just stay in that
terminal window to run the program.
